### ISSUE TITLE
Failed to generate .proto when OAI v3 component name contains "map"

### ISSUE THREAD

**Issue by rodherz** [rodherz/gnostic-grpc#3]
map_data_view:
        $ref: '#/components/schemas/map_data_view'

    map_data_view:
      description: |
        The data view name used to filter out map data which should not be supported.
      type: string

Plugin error: [file "directionv9.proto" included an unresolvable reference to "directionv9.map[string]Ew"]

**Comment by jiazhanfeng1989** [comment]
Thanks for your quickly support, the tn-v0.8.1 version works well.
